# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: resource.proto for package 'stamp'

require 'grpc'
require 'resource_pb'

module Stamp
  module Api
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'stamp.Api'

      rpc :Access, AccessRequest, AccessResponse
      rpc :AccessConfirmation, AccessConfirmationRequest, AccessConfirmationResponse
    end

    Stub = Service.rpc_stub_class
  end
end
