# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: 10
  timeout: 5000
  url: <%= ENV['DATABASE_URL'] %>

test:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") { 'stamp_test' } %>

development:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") { 'stamp_development' } %>

staging:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") { 'stamp_staging' } %>

pre_production:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") { 'stamp_pre_production' } %>

production:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") { 'stamp_production' } %>
