# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resource.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "stamp.AccessRequest" do
    optional :accessing_user, :int64, 1
    optional :resource_owner, :int64, 2
    repeated :medical_record, :int64, 3
  end
  add_message "stamp.AccessResponse" do
    optional :status, :enum, 1, "stamp.Status"
    optional :message, :string, 2
  end
  add_message "stamp.AccessConfirmationRequest" do
    optional :accessing_user, :int64, 1
    optional :resource_owner, :int64, 2
    repeated :medical_record, :int64, 3
    optional :status, :enum, 4, "stamp.Status"
  end
  add_message "stamp.AccessConfirmationResponse" do
    optional :message, :string, 1
  end
  add_enum "stamp.Status" do
    value :GRANTED, 0
    value :AWAITING_RESPONSE, 1
    value :ACCESS_DENIED, 2
  end
end

module Stamp
  AccessRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("stamp.AccessRequest").msgclass
  AccessResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("stamp.AccessResponse").msgclass
  AccessConfirmationRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("stamp.AccessConfirmationRequest").msgclass
  AccessConfirmationResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("stamp.AccessConfirmationResponse").msgclass
  Status = Google::Protobuf::DescriptorPool.generated_pool.lookup("stamp.Status").enummodule
end
